swagger: "2.0"
info:
  version: "0.0.1"
  title: Ayopop API-Gateway
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
  
paths:
            
  /members/login:
    x-swagger-router-controller: AuthController
    post:
      description: Performs a User authentication with Ayopop System - validate the user is authenticated
      operationId: memberLogin
      parameters:
        - name: usermetadata
          in: body
          description: The input for memebers login
          schema:
            $ref: "#/definitions/UserMeta" 
      responses:
            "200":
              description: Success
              schema:
                $ref: "#/definitions/MembersLoginResponse"
            default:
              description: Error
              schema:
                $ref: "#/definitions/ErrorResponse"
      tags:
        - members     
        
  /members/ping:
    x-swagger-router-controller: Misc_Controller
    get:
      description: Performs a pingcheck on a service from API-Gateway
      operationId: membersPingCheck
      parameters:
        - name: name
          in: query
          description: The test argument
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PingCheckResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - members
        
  /members/greet:
    x-swagger-router-controller: Misc_Controller
    get:
      description: Performs a pingcheck on a service from API-Gateway
      operationId: greet
      parameters:
        - name: name
          in: query
          description: The name of person to say Hi to.
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PingCheckResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - members
            
  /services/pingall:
    x-swagger-router-controller: Misc_Controller
    get:
      description: Performs a pingcheck on a service from API-Gateway
      operationId: pingAllServices
      parameters:
        - name: name
          in: query
          description: Test data to send.
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PingCheckResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /auth/login:
    x-swagger-router-controller: AuthController
    post:
      description: Performs login and return a encoded token or opaque
      operationId: generateauthtoken
      parameters:
        - name: usermetadata
          in: body
          description: The input for authetication 
          schema:
            $ref: "#/definitions/User" 
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PingCheckResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - auth
        
  /ayosaldo/ping:
    x-swagger-router-controller: Misc_Controller
    get:
      description: Performs a pingcheck on a service from API-Gateway
      operationId: pingCheck
      parameters:
        - name: name
          in: query
          description: The name of the service to perform the pingcheck 
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PingCheckResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags: 
        - ayosaldo
        
  /swagger:
    x-swagger-pipe: swagger_raw
    
definitions:
  MembersLoginResponse:
    properties:
      success:
        type: boolean
      data:
        type: object
        
  PingCheckResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  UserMeta:
   properties:
      phone:
        type: string
      password:
        type: string
      header:
        type: object
  User:
   properties:
      phone:
        type: string
      password:
        type: string