swagger: "2.0"
info:
  version: "0.0.1"
  title: Ayopop API-Gateway
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /ayosaldo/ping:

    x-swagger-router-controller: Misc_Controller
    get:
      description: Performs a pingcheck on a service from API-Gateway
      tags: 
        - ayosaldo
      operationId: pingCheck
      parameters:
        - name: name
          in: query
          description: The name of the service to perform the pingcheck 
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PingCheckResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /members/login:
        # binds a127 app logic to a route
        x-swagger-router-controller: AuthController
        post:
          description: Performs a User authentication with Ayopop System - validate the user is authenticated
          # used as the method name of the controller
          operationId: memberLogin
          parameters:
            - name: phone
              in: query
              description: The name of the service to perform the pingcheck
              required: false
              type: string
          responses:
            "200":
              description: Success
              schema:
                # a pointer to a definition
                $ref: "#/definitions/MembersLoginResponse"
            # responses may fall through to errors
            default:
              description: Error
              schema:
                $ref: "#/definitions/ErrorResponse"
  /members/ping:
    x-swagger-router-controller: Misc_Controller
    get:
      description: Performs a pingcheck on a service from API-Gateway
      operationId: membersPingCheck
      parameters:
        - name: name
          in: query
          description: The test argument
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PingCheckResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /members/greet:
    x-swagger-router-controller: Misc_Controller
    get:
      description: Performs a pingcheck on a service from API-Gateway
      operationId: greet
      parameters:
        - name: name
          in: query
          description: The name of person to say Hi to.
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PingCheckResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /v1/pingall:
    x-swagger-router-controller: Misc_Controller
    get:
      description: Performs a pingcheck on a service from API-Gateway
      operationId: pingAllServices
      parameters:
        - name: name
          in: query
          description: Test data to send.
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PingCheckResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /servicex/ping:
    x-swagger-router-controller: Misc_Controller
    get:
      description: Performs a pingcheck on a service from API-Gateway
      operationId: servicxPingCheck
      parameters:
        - name: name
          in: query
          description: The name of the service to perform the pingcheck 
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PingCheckResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /auth/login:
    x-swagger-router-controller: AuthController
    post:
      description: Performs login and return a encoded token
      operationId: generateauthtoken
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PingCheckResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - auth
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  MembersLoginResponse:
    properties:
      success:
        type: boolean
      data:
        type: object
        
  PingCheckResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
