swagger: "2.0"
info:
  version: "0.0.1"
  title: Ayopop API-Gateway
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
  
paths:
            
  /members/login:
    x-swagger-router-controller: AuthController
    post:
      description: Performs a User authentication with Ayopop System - validate the user is authenticated
      operationId: memberLogin
      parameters:
        - name: usermetadata
          in: body
          description: The input for memebers login
          schema:
            $ref: "#/definitions/UserMeta" 
      responses:
            "200":
              description: Success
              schema:
                $ref: "#/definitions/MembersLoginResponse"
            default:
              description: Error
              schema:
                $ref: "#/definitions/ErrorResponse"
      tags:
        - members
  /members/verifyAccount:
    x-swagger-router-controller: AuthController
    post:
      description: This function will verify the members account with ayopop system # used as the method name of the controller
      operationId: verifyAccount
      parameters:
        - name: phone
          in: query
          description: The name of the service to perform the pingcheck
          required: false
          type: string
      responses:
            "200":
              description: Success
              schema:
                $ref: "#/definitions/MembersLoginResponse"  # a pointer to a definition
            default:
              description: Error
              schema:
                $ref: "#/definitions/ErrorResponse"
      tags:
        - members
  /members/verifyAccessToken:
    x-swagger-router-controller: AuthController
    post:
      description: This function will verify the Social Auth token and is valid or not # used as the method name of the controller
      operationId: verifyAccessToken
      parameters:
        - name: accessToken
          in: query
          description: The name of the service to perform the pingcheck
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/MembersLoginResponse"  # a pointer to a definition
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - members
  /members/verifyOTP:
    x-swagger-router-controller: AuthController
    post:
      description: This function will verify the otp # used as the method name of the controller
      operationId: verifyOTP
      parameters:
        - name: OTP
          in: query
          description: the function will verify otp is valid or not
          required: false
          type: string
        - name: phoneNumber
          in: query
          description: the function will verify otp is valid or not
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/MembersLoginResponse"  # a pointer to a definition
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - members
  /members/resendOTP:
    x-swagger-router-controller: AuthController
    post:
      description: This function will resend the otp # used as the method name of the controller
      operationId: resendOTP
      parameters:
        - name: OTP
          in: query
          description: the function will resend the new otp
          required: false
          type: string
        - name: phoneNumber
          in: query
          description: valid phone number which is linked to your account
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/MembersLoginResponse"  # a pointer to a definition
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - members
  /members/verifyPin:
    x-swagger-router-controller: AuthController
    post:
      description: This function will verify the pin # used as the method name of the controller
      operationId: verifyPin
      parameters:
        - name: phoneNumber
          in: query
          description: phone number which is linked to your account
          required: false
          type: string
        - name: pin
          in: query
          description: pin used to validate accound
          required: false
          type: string
        - name: type
          in: query
          description: type used to check reset or verify
          required: false
          type: string
        - name: newPin
          in: query
          description: newPin used to reset or verify
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/MembersLoginResponse"  # a pointer to a definition
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - members
  /members/registerAPI:
    x-swagger-router-controller: AuthController
    post:
      description: This function will update user info # used as the method name of the controller
      operationId: registerAPI
      parameters:
        - name: phoneNumber
          in: query
          description: phone number which is linked to your account
          required: false
          type: string
        - name: typeIndex
          in: query
          description: type index
          required: false
          type: string
        - name: ageRange
          in: query
          description: user age
          required: false
          type: string
        - name: newPin
          in: query
          description: newPin used to reset or verify
          required: false
          type: string
        - name: language
          in: query
          description: user language
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/MembersLoginResponse"  # a pointer to a definition
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - members
  /members/forgotPin:
    x-swagger-router-controller: AuthController
    post:
      description: This function will send otp and reset pin # used as the method name of the controller
      operationId: forgotPin
      parameters:
        - name: phoneNumber
          in: query
          description: phone number which is linked to your account
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/MembersLoginResponse"  # a pointer to a definition
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - members
  /members/ping:
    x-swagger-router-controller: Misc_Controller
    get:
      description: Performs a pingcheck on a service from API-Gateway
      operationId: membersPingCheck
      parameters:
        - name: name
          in: query
          description: The test argument
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PingCheckResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - members
        
  /members/greet:
    x-swagger-router-controller: Misc_Controller
    get:
      description: Performs a pingcheck on a service from API-Gateway
      operationId: greet
      parameters:
        - name: name
          in: query
          description: The name of person to say Hi to.
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PingCheckResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - members
            
  /services/pingall:
    x-swagger-router-controller: Misc_Controller
    get:
      description: Performs a pingcheck on a service from API-Gateway
      operationId: pingAllServices
      parameters:
        - name: name
          in: query
          description: Test data to send.
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PingCheckResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /auth/generateToken:
    x-swagger-router-controller: AuthController
    post:
      description: Verifies auth pin and returns a encoded token.
      operationId: generateToken
      parameters:
        - name: Credentials
          in: body
          description: The input credentials for authetication 
          schema:
            $ref: "#/definitions/AuthInput" 
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AuthResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - auth
        
  /ayosaldo/ping:
    x-swagger-router-controller: Misc_Controller
    get:
      description: Performs a pingcheck on a service from API-Gateway
      operationId: pingCheck
      parameters:
        - name: name
          in: query
          description: The name of the service to perform the pingcheck 
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PingCheckResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags: 
        - ayosaldo
        
  /swagger:
    x-swagger-pipe: swagger_raw
    
definitions:
  MembersLoginResponse:
    properties:
      success:
        type: boolean
      data:
        type: object
        
  PingCheckResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  UserMeta:
   properties:
      phone:
        type: string
      password:
        type: string
      header:
        type: object
  AuthInput:
   properties:
      phone:
        type: string
      pin:
        type: string
   example:   # Sample object
      phone: 918859564575
      pin: 123456
  AuthResponse:
   properties:
      token:
       type : string